### ISSUE TITLE
trash-cli prefers $topdir/.Trash-$uid to the trash directory over $topdir/.Trash/$uid

### ISSUE THREAD

**Issue by ncaq** [andreafrancia/trash-cli#108]
~~~sh
2017-10-15T22:21:11 ncaq@akaza/pts/7(0) /mnt/usbstick
% ll
合計 68K
drwxrwxrwx 1 root root  64K 10月 15 22:20 ./
drwxr-xr-x 9 root root 4.0K 10月 16  2015 ../
2017-10-15T22:21:11 ncaq@akaza/pts/7(0) /mnt/usbstick
% touch example
2017-10-15T22:21:17 ncaq@akaza/pts/7(0) /mnt/usbstick
% ll
合計 68K
drwxrwxrwx 1 root root  64K 10月 15 22:21 ./
drwxr-xr-x 9 root root 4.0K 10月 16  2015 ../
-rwxrwxrwx 1 root root    0 10月 15 22:21 example*
2017-10-15T22:21:19 ncaq@akaza/pts/7(0) /mnt/usbstick
% trash-put example
2017-10-15T22:21:31 ncaq@akaza/pts/7(0) /mnt/usbstick
% tree -a 
.
└── [drwxrwxrwx  240]  .Trash-1000/
    ├── [drwxrwxrwx  144]  files/
    │   └── [-rwxrwxrwx    0]  example*
    └── [drwxrwxrwx  168]  info/
        └── [-rwxrwxrwx   59]  example.trashinfo*

3 directories, 2 files
~~~

trash-cli uses `$topdir/.Trash-$uid` but not `$topdir/.Trash/$uid`.
I read [Trash specification](https://specifications.freedesktop.org/trash-spec/trashspec-latest.html)
I thought `$topdir/.Trash/$uid` is more compliant with `$topdir/.Trash-$uid`

Even if trash-cli emphasizes compatibility with gio rather than specification, comments are inconsistent.

> Trash a file in the appropriate trash directory.
> If the file belong to the same volume of the trash home directory it
> will be trashed in the home trash directory.
> Otherwise it will be trashed in one of the relevant volume trash
> directories.
> Each volume can have two trash directories, they are
>     - $volume/.Trash/$uid
>     - $volume/.Trash-$uid
> Firstly the software attempt to trash the file in the first directory
> then try to trash in the second trash directory.
>
> [trash-cli/put.py at master · andreafrancia/trash-cli](https://github.com/andreafrancia/trash-cli/blob/master/trashcli/put.py#L133)

Thanks.

**Comment by yumetodo** [comment]
@ncaq I read [GNU/Linuxにおけるゴミ箱ディレクトリは.Trash/$uid/と.Trash-$uid/のどちらが正しいのか調べていたらtrash-cliのコメントが動作と違ったのでissueを開きました - ncaq](https://www.ncaq.net/2017/10/15/).

>I read Trash specification
I thought `$topdir/.Trash/$uid` is more compliant with `$topdir/.Trash-$uid`

Trash specification says that when the implementation trash files from the rest of the file system (device/partition), that has “home trash” directory, because of copy cost, the implementation MAY use `$topdir/.Trash/$uid` and `$topdir/.Trash-$uid`.

>https://specifications.freedesktop.org/trash-spec/trashspec-latest.html
>The following paragraph applies ONLY to the case when the implementation supports trashing in the top directory, and a $topdir/.Trash does not exist or has not passed the checks:

**this description is important** to resolve behavior, I think. 

1. Creating `$topdir/.Trash` is only permitted for an administrator(the “sticky bit” in the permissions must be set).
2.  All user MUST have write access partition to `$topdir/.Trash`.
3. When `$topdir/.Trash` exist and pass all checks(“sticky bit”, not a symbolic link, etc. watch Trash specification),
    1. A user can create `$topdir/.Trash/$uid`(the implementation MUST immediately create it).
    2. A user can use `$topdir/.Trash/$uid` as trash directory
4. When `$topdir/.Trash` **doesn't exist** or fail the checks,
    1. A user can create `$topdir/.Trash-$uid`(the implementation MUST immediately create it)
    2. A user can use `$topdir/.Trash-$uid` as trash directory

As far as I know, your investigation is the case when `$topdir/.Trash` is not created by administrator. In this case, the behavior that the implementation use `$topdir/.Trash-$uid` is correct.

**Comment by ncaq** [comment]
I misread Spec.
I understand to implementation and comment of trash-cli is correct.
Thank @yumetodo .
I close this issue.
