### ISSUE TITLE
Add warning to alert when no trash exists, and deletion will be permanent. 

### ISSUE THREAD

**Issue by yegnal** [andreafrancia/trash-cli#265]
**Is your feature request related to a problem? Please describe.**
Not really a problem per se, but I I've used the command on a directory that didn't have a trash directory..  The file/folder was deleted, no warning given that file would be lost.

**Describe the solution you'd like**
I think it would be useful to have a warning when file will be deleted where no trash exists, Y/n prompt to confirm permanent deletion...

**Comment by andreafrancia** [comment]
`trash-cli` does not (shouldnt) delete the file if no trash exists.
Please use the template below to provide more specific information about your issue.

```
**Describe the bug**
A clear and concise description of what the bug is.

**trash-cli version**
Output of: trash-put --version

**Are you using the latest version of trash-cli?**
Yes/no

**Have you tried if the bug is present in the latest version of trash-cli?**
Yes/no

**Please, install the latest version of trash-cli and try again before submitting the bug**

First of all you need to uninstall any previous version of trash-cli::

    $ [sudo] pip uninstall trash-cli # remove the previous version (with pip)
    $ [sudo] apt-get remove trash-cli # remove the previous version (with apt)
    $ [sudo] yum uninstall trash-cli # remove the previous version (with yum)
    $ ... # refer to the package manager of your distribution

Then install the latest version from git::

    $ pip install pip install git+https://github.com/andreafrancia/trash-cli

Have done that? Then continue with the bug report.

**Operating system:**
 - OS: [e.g. Debian, Ubuntu, Fedora, macOs, Cygwin]

**To Reproduce**
Copy and paste the commands (and their output) to execute in order to reproduce 
the behavior:

$ touch foo
$ trash-put foo
$ ls foo
ls: cannot access 'foo': No such file or directory
$ trash-list
2020-12-13 18:36:21 /Users/andrea/trash-cli/foo

**Expected behavior**
A clear and concise description of what you expected to happen.

**Volumes detail**
If your issue is related to recognition of volumes, please provide the output 
of: `trash-list --debug-volumes` 
```

**Comment by yegnal** [comment]
Dowoaded from Fedora 37 repository, it will delete without warning if no "trash" for a given volume exists, and trash if one does.
You can figure it out from there, I would need to be a software engineer from the looks of your email to reply up to the standard you're expecting.



    On Thursday, November 24, 2022 at 09:38:35 AM EST, Andrea Francia ***@***.***> wrote:  
 
 


trash-cli does not (shouldnt) delete the file if no trash exists.
Please use the template below to provide more specific information about your issue.
**Describe the bug**
A clear and concise description of what the bug is.

**trash-cli version**
Output of: trash-put --version

**Are you using the latest version of trash-cli?**
Yes/no

**Have you tried if the bug is present in the latest version of trash-cli?**
Yes/no

**Please, install the latest version of trash-cli and try again before submitting the bug**

First of all you need to uninstall any previous version of trash-cli::

    $ [sudo] pip uninstall trash-cli # remove the previous version (with pip)
    $ [sudo] apt-get remove trash-cli # remove the previous version (with apt)
    $ [sudo] yum uninstall trash-cli # remove the previous version (with yum)
    $ ... # refer to the package manager of your distribution

Then install the latest version from git::

    $ pip install pip install git+https://github.com/andreafrancia/trash-cli

Have done that? Then continue with the bug report.

**Operating system:**
 - OS: [e.g. Debian, Ubuntu, Fedora, macOs, Cygwin]

**To Reproduce**
Copy and paste the commands (and their output) to execute in order to reproduce 
the behavior:

$ touch foo
$ trash-put foo
$ ls foo
ls: cannot access 'foo': No such file or directory
$ trash-list
2020-12-13 18:36:21 /Users/andrea/trash-cli/foo

**Expected behavior**
A clear and concise description of what you expected to happen.

**Volumes detail**
If your issue is related to recognition of volumes, please provide the output 
of: `trash-list --debug-volumes`

**Comment by andreafrancia** [comment]
Without that information I can't help you sorry.

**Comment by andreafrancia** [comment]
I'm trying to be more clear.

trash-cli does not delete files

If you are experiencing that there should be a problem. I don't have access to your computer and I've not seen the problem you are reporting.

It may be that the problem your are experiencing is related to your particular system configuration, to something you don't know, or something that is not working.

I cannot interviene if I cannot see what is happening in your computer and how you are using it.

I also need to know the exact version of trash-cli you are using. 
I do not control what Fedora is putting in their repositories, and I do not know which version is on your computer, so the only way to know which version of trash-cli you are using is the instructions I leave below.

If you need help ran this command in your terminal and then send me the output message:
```
trash-put --version
```

After that I need to know which command are you using, I cannot help you if I don't know how you are using trash-cli.
If you think I need my help do the following.

Create a text file named `pippo.txt`:
```
echo ciao > pippo.txt
```

Then trash it using the verbose mode:
```
trash-put -v pippo.txt
```

Then run `trash-list`:
```
trash-list
```

Then run this command 
```
trash-list --debug-volumes
```

I need to know the result of each of this command in order to understand what is happening, so I need for each command you copy from your terminal the command invocation and the result.

**Comment by yegnal** [comment]
I don't need help,  developers of a project should be welcoming to information that leads to improvements, and curious when bugs are suspected. 
How hard would it be to create a fedora 37 VM, install trash-cli and check it out.   Create a volume without an attached .trash directory..
If you don't want to,  that's on you
    On Thursday, November 24, 2022 at 10:56:59 AM EST, Andrea Francia ***@***.***> wrote:  
 
 


Without that information I can't help you sorry.

**Comment by andreafrancia** [comment]
Thank for your time. I don't need your suggestion on how handle this project. Please do not report bugs anymore without the information I asked you.
