### ISSUE TITLE
Select many files in `trash-restore`

### ISSUE THREAD

**Issue by DSIW** [andreafrancia/trash-cli#30]
Index selection via
- `x..z`
- `x-z`
- `x y z` will use files at index x, y and z.

**Comment by chronometric** [comment]
This feature seems like a fairly essential interface convenience right now. Instead of scanning through the list of files once and typing the numbers I want to retrieve, I'm typing one number at a time, re-starting the program, using the mouse to scroll up the list pick out the next file, & etc

(The only way I could speed this up would be to write down the numbers of the files on a single read-through, and then work in reverse order so deleting earlier files didn't change the file numbers)

In issue #22 the range function was said to be a bad idea. I suppose that the range function is of limited use, since the files are not sorted in a useful order. But at least some implementation of this seems highly essential to facilitating the program's primary function upon more than one deleted file.

What objections are there to a multiple selection restore?

**Comment by andreafrancia** [comment]
> What objections are there to a multiple selection restore?

If you think a feature is essential please do it: you are free to fork and implement the feature.

**Comment by chronometric** [comment]
@andreafrancia: I don't code. I'm sorry if my suggestion was out of line somehow; I was simply trying to articulate why the absence of this feature makes your otherwise excellent program increasingly awkward as its usage scales. 

Since it's probably the most popular feature request, I thought it would be interesting and perhaps helpful to hear why you said it is undesirable, but you are obviously under no obligation to respond.

**Comment by andreafrancia** [comment]
Probably the problem is that nobody with enough programming skill is commited to implement this feature.

Unfortunately I don't have time to understand the request nor to implement the feature, sorry. I wrote trash-cli before I got married, now I'm father of two.

The proposed solution for multiple selection seems awkward to me. The whole restore-trash is awkward. I would have created it exploiting shell-like globbing instead of indexing.

**Comment by arendu** [comment]
@chronometric you can try my branch here: https://github.com/arendu/trash-cli

It allows giving a comma seperated list of indexes to restore.

@andreafrancia I have submitted a pull request. Thank you for created this tool!

**Comment by andreafrancia** [comment]
@arendu: thank you for proposing a solution.
I don't know if I can find the enough amount of time, focus and working linux system for reviewing your pull request design and implications at a level I can decide to merge it.
But everyone I think that everyone is free to checkout your version and use it if it fits they needs so I'm glad to you.

**Comment by Link-Satonaka** [comment]
Why not just copy the code from `trash-rm [pattern]` to add pattern matching to restore: `trash-restore [pattern]`?

If the code cannot be so easily merged with the existing `trash-restore`, you could just make a `trash-restore-pattern [pattern]` function and call it a day.
