### ISSUE TITLE
trash-empty should ask for confirmation

### ISSUE THREAD

**Issue by amishmm** [andreafrancia/trash-cli#32]
when i do trash-empty it instantly empties the trash.

instead of doing this, it should ask, "Are you sure?".

you may add -f option which will NOT ask that question.

please implement this.

thank you

**Comment by afcuttin** [comment]
I agree.
Another option is for `trash-empty` to require a mandatory argument, like `trash-empty 0` to clean everything.
If no argument is provided, the help can be shown.

**Comment by potherca** [comment]
Instead of stating "it should be thus" can either of you explain the rationale *why* it should be so?

**Comment by amishxda** [comment]
Because it can be run by accident?

Whole purpose of trash-cli to avoid accidental deletion and easy recovery in such cases.

So trash-empty can also be run by mistake.

Say for example instead typing trash-r<TAB><ENTER> I type trash-e<TAB><ENTER> (E and R are very close on keyboard)

Now tab completion will run trash-empty instead of trash-rm and EMPTY whole trash accidentally.

So confirmation like "Are you sure, you want to empty trash" should exist by default.

I know this can be done by shell function over-riding actual trash-empty command (which is what I have done) but in my opinion it should be default. as it is otherwise a complete destruction without confirmation! :)

**Comment by potherca** [comment]
@andreafrancia Do you have any opinions on the matter?

**Comment by andreafrancia** [comment]
@potherca it would be a good idea but it would break the retro-compatibility

**Comment by potherca** [comment]
Maybe the best way to go is for users that require a confirmation to use an alias for `trash-empty`?

**Comment by GregTheHun** [comment]
> @Potherca it would be a good idea but it would break the retro-compatibility

I'm confused which "retro-compatibility" this might be referring to?

**Comment by asakura42** [comment]
I use this function: 

```
trash-empty () {
  /usr/bin/trash-list
  echo ""
  echo -n "Continue? "
  read REPLY

  if [[ $REPLY =~ ^[Yy]$ ]]
  then
	/usr/bin/trash-empty $1
  fi
}
```

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I vote for #Close because of backwards-compatibility. I assume there are a lot of scripts using `trash-cli` that would broke when such a security-question is added as default behavior.

`trash-cli` is not for Windows or Apple users. ;)

The trash-can itself is a "security layer". So the file stil was "deleted" in a conceptual way. Now asking the user again if she/he really want's to delete a deleted file...

**Comment by andreafrancia** [comment]
Since commit 2fad485 trash-empty asks for confirmation when standard input is interactive. When standard input is not interactive (e.g. trash-empty is launched from a script) it keeps the old behaviour.
