### ISSUE TITLE
Cannot install trash-cli on SuSE Linux Enterprise Server 10

### ISSUE THREAD

**Issue by khaister** [andreafrancia/trash-cli#37]
I wanted to install trash-cli from source on server which runs SuSE Linux Enterpise Server 10 (64b). I got the following error:

<pre># python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in ?
    from distutils.core import setup
ImportError: No module named distutils.core
</pre>

I'm using python 2.4.2.

**Comment by andreafrancia** [comment]
Unfortunately for trash-cli the Python 2.4.2 is a bit old version of Python. I developed trash-cli using python 2.7 on Ubuntu, and it is possible that something will not work using an older python and/or a different Linux distribution.

I suggest you to check out the documentation of your distribution in order to get python 2.6 to work.
