### ISSUE TITLE
trash-put returns 0 even if the file could not be "deleted" in a correct way

### ISSUE THREAD

**Issue by Ganton** [andreafrancia/trash-cli#40]
Hi!

`trash-put 0.12.7` returns `0` even if the file could not be "deleted" in a correct way. For example:

```
$ trash-put /INEXISTENT_FILE; echo $?
trash-put: cannot trash non existent `/INEXISTENT_FILE'
0
```

and that forbids developments like 

```
trash-put "$file" || manage_error
```

However:

```
$ rm /INEXISTENT_FILE; echo $?
rm: /INEXISTENT_FILE: No such file or directory
1
```

and that allows developments like 

```
rm "$file" || manage_error
```

_In other words_:
If trash-put finds a problem deleting a file, it should not return 0 because it has found an error. 

If trash-put returned "1" in the prior example, as `rm` does, it should be an advantage, as it allows a better `rm` replacement, and it follows better the standards.

I suppose that it should be easy to solve :-)

Anyway, thanks for the good trash-cli software! Keep up the good work!

**Comment by XuKunL** [comment]
if
`rm /tmp/11111;echo $?`
`1`
if
`rm -f /tmp/1111 ; echo $?`
`0`
so  trash-put   nedd this

**Comment by DrupaListo-com** [comment]
the bug is valid for 0.12.7 - the trash-cli version that is in the current latest in debian repos.
Actually I find that in some debian versions its 0.12.9
see: https://packages.debian.org/search?keywords=trash-cli

but most probably the same bug is there too.

I recommend you all use trash cli 0.16.12.28 or similar recent version where I tested and when deleting a non existent file I got error code 74 which is ok.

To upgrade to trashcli 0.16* first do 
`apt-get remove trash-cli`
or even
`apt-get purge trash-cli` # (removes config files too if any)

then install as per README: https://github.com/andreafrancia/trash-cli

```
git clone https://github.com/andreafrancia/trash-cli.git
cd trash-cli
sudo python setup.py install

```

Bug can be closed now.

We need newer 0.16 packages pushed to debian repos.
